services:
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:

54327:5432
  environment:
POSTGRES_PASSWORD=wp@010605
POSTGRES_USER=wattanapat
POSTGRES_DB=wattanapat
volumes:
./data:/var/lib/postgresql/data
